FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

COPY . .

CMD ["uvicorn", "app.main:app", "--host","0.0.0.0", "--port", "8000"]
